const COPY = {
  en: { warning: "Illegal, sexually explicit, or copyright-infringing content may be removed and may result in account restrictions or penalties under applicable law.", imageLimit: "Images only · Original file up to 2MB (automatically optimized)", mediaUrl: "Image or video URL (YouTube supported)", mediaHelp: "Local video uploads are not supported. To use video, paste a YouTube or direct video URL." },
  ko: { warning: "불법·음란물·저작권 침해 콘텐츠를 올리면 게시물 삭제, 이용 제한 및 관련 법률에 따른 처벌을 받을 수 있습니다.", imageLimit: "이미지만 업로드 가능 · 원본 2MB 이하 (자동 최적화)", mediaUrl: "이미지·영상 URL (YouTube 지원)", mediaHelp: "영상 파일 업로드는 지원하지 않습니다. 영상은 YouTube 또는 직접 영상 URL을 입력해주세요." },
  ja: { warning: "違法・性的・著作権侵害コンテンツを投稿すると、削除、利用制限、法令に基づく処罰の対象となる場合があります。", imageLimit: "画像のみ・元ファイル2MB以下（自動最適化）", mediaUrl: "画像・動画URL（YouTube対応）", mediaHelp: "動画ファイルのアップロードには対応していません。YouTubeまたは動画URLを入力してください。" },
  zh: { warning: "上传违法、色情或侵犯版权的内容可能会被删除、限制使用，并依法受到处罚。", imageLimit: "仅限图片・原文件不超过2MB（自动优化）", mediaUrl: "图片或视频网址（支持YouTube）", mediaHelp: "不支持本地视频上传。请粘贴YouTube或直接视频网址。" },
  es: { warning: "El contenido ilegal, sexualmente explícito o que infrinja derechos de autor podrá eliminarse y causar restricciones o sanciones legales.", imageLimit: "Solo imágenes · Original de hasta 2 MB (optimización automática)", mediaUrl: "URL de imagen o vídeo (compatible con YouTube)", mediaHelp: "No se admiten vídeos locales. Pega una URL de YouTube o de vídeo directo." },
  fr: { warning: "Tout contenu illégal, sexuellement explicite ou portant atteinte aux droits d’auteur peut être supprimé et entraîner des restrictions ou sanctions légales.", imageLimit: "Images uniquement · original jusqu’à 2 Mo (optimisation automatique)", mediaUrl: "URL d’image ou de vidéo (YouTube pris en charge)", mediaHelp: "L’importation locale de vidéos n’est pas prise en charge. Collez une URL YouTube ou vidéo directe." },
  vi: { warning: "Nội dung bất hợp pháp, khiêu dâm hoặc vi phạm bản quyền có thể bị xóa và dẫn đến hạn chế tài khoản hoặc xử phạt theo pháp luật.", imageLimit: "Chỉ hình ảnh · tệp gốc tối đa 2MB (tự động tối ưu)", mediaUrl: "URL hình ảnh hoặc video (hỗ trợ YouTube)", mediaHelp: "Không hỗ trợ tải video từ máy. Hãy dán URL YouTube hoặc URL video trực tiếp." },
  de: { warning: "Illegale, sexuell explizite oder urheberrechtsverletzende Inhalte können entfernt werden und zu Einschränkungen oder rechtlichen Strafen führen.", imageLimit: "Nur Bilder · Original bis 2 MB (automatisch optimiert)", mediaUrl: "Bild- oder Video-URL (YouTube unterstützt)", mediaHelp: "Lokale Video-Uploads werden nicht unterstützt. Bitte YouTube- oder direkte Video-URL einfügen." },
  ru: { warning: "Незаконный, откровенный или нарушающий авторские права контент может быть удалён и повлечь ограничения или ответственность по закону.", imageLimit: "Только изображения · оригинал до 2 МБ (автооптимизация)", mediaUrl: "URL изображения или видео (поддерживается YouTube)", mediaHelp: "Локальная загрузка видео не поддерживается. Вставьте ссылку YouTube или прямую ссылку на видео." },
  id: { warning: "Konten ilegal, seksual eksplisit, atau melanggar hak cipta dapat dihapus dan mengakibatkan pembatasan akun atau sanksi hukum.", imageLimit: "Hanya gambar · file asli maks. 2MB (dioptimalkan otomatis)", mediaUrl: "URL gambar atau video (mendukung YouTube)", mediaHelp: "Unggahan video lokal tidak didukung. Tempel URL YouTube atau URL video langsung." },
  pt: { warning: "Conteúdo ilegal, sexualmente explícito ou que viole direitos autorais poderá ser removido e resultar em restrições ou sanções legais.", imageLimit: "Somente imagens · original até 2 MB (otimização automática)", mediaUrl: "URL de imagem ou vídeo (compatível com YouTube)", mediaHelp: "Vídeos locais não são aceitos. Cole uma URL do YouTube ou de vídeo direto." },
  hi: { warning: "अवैध, अश्लील या कॉपीराइट का उल्लंघन करने वाली सामग्री हटाई जा सकती है और खाते पर रोक या कानूनी दंड लग सकता है।", imageLimit: "केवल चित्र · मूल फ़ाइल अधिकतम 2MB (स्वचालित अनुकूलन)", mediaUrl: "चित्र या वीडियो URL (YouTube समर्थित)", mediaHelp: "स्थानीय वीडियो अपलोड समर्थित नहीं है। YouTube या सीधे वीडियो का URL डालें।" },
  tr: { warning: "Yasa dışı, müstehcen veya telif hakkını ihlal eden içerikler kaldırılabilir ve hesap kısıtlaması ya da yasal yaptırım uygulanabilir.", imageLimit: "Yalnızca görsel · orijinal en fazla 2 MB (otomatik optimize edilir)", mediaUrl: "Görsel veya video URL’si (YouTube desteklenir)", mediaHelp: "Yerel video yükleme desteklenmez. YouTube veya doğrudan video URL’si yapıştırın." },
  th: { warning: "เนื้อหาที่ผิดกฎหมาย ลามกอนาจาร หรือละเมิดลิขสิทธิ์อาจถูกลบ จำกัดการใช้งาน หรือได้รับโทษตามกฎหมาย", imageLimit: "เฉพาะรูปภาพ · ไฟล์ต้นฉบับไม่เกิน 2MB (ปรับขนาดอัตโนมัติ)", mediaUrl: "URL รูปภาพหรือวิดีโอ (รองรับ YouTube)", mediaHelp: "ไม่รองรับการอัปโหลดวิดีโอจากเครื่อง โปรดใส่ URL YouTube หรือ URL วิดีโอโดยตรง" },
  ar: { warning: "قد يُحذف المحتوى غير القانوني أو الجنسي الصريح أو المنتهك لحقوق النشر، وقد يؤدي إلى تقييد الحساب أو عقوبات قانونية.", imageLimit: "صور فقط · الملف الأصلي حتى 2MB (تحسين تلقائي)", mediaUrl: "رابط صورة أو فيديو (يدعم YouTube)", mediaHelp: "رفع الفيديو من الجهاز غير مدعوم. ألصق رابط YouTube أو رابط فيديو مباشر." },
  bn: { warning: "অবৈধ, যৌনভাবে স্পষ্ট বা কপিরাইট লঙ্ঘনকারী কনটেন্ট মুছে ফেলা হতে পারে এবং অ্যাকাউন্ট সীমাবদ্ধতা বা আইনি শাস্তি হতে পারে।", imageLimit: "শুধু ছবি · মূল ফাইল সর্বোচ্চ 2MB (স্বয়ংক্রিয় অপ্টিমাইজেশন)", mediaUrl: "ছবি বা ভিডিও URL (YouTube সমর্থিত)", mediaHelp: "লোকাল ভিডিও আপলোড সমর্থিত নয়। YouTube বা সরাসরি ভিডিও URL দিন।" },
};

export function getCreatorSafetyCopy(lang) {
  return COPY[String(lang || "en").split("-")[0]] || COPY.en;
}

export const creatorWarningStyle = {
  padding: "13px 16px", border: "1.5px solid #f2b8bd", borderRadius: 10,
  background: "#fff5f5", color: "#9f2632", fontWeight: 800, lineHeight: 1.55,
};
