const EN = {
  title: "Quiz", intro: "Play quizzes about your favorite topics or create your own.", create: "Create Quiz",
  search: "Search quizzes", popular: "Popular", latest: "Latest", empty: "No quizzes match these filters.", loading: "Loading...",
  all: "All", game: "Games", entertainment: "Entertainment", animation: "Anime / Manga", food: "Food", sports: "Sports",
  knowledge: "Knowledge", other: "Other", questions: "questions", plays: "plays", featured: "Featured Quizzes", allQuizzes: "All Quizzes",
  quizList:"Quiz list", resultTitle:"Quiz Result", accuracy:"Accuracy", retry:"Retry", retryWrong:"Retry wrong answers", randomQuiz:"Random quiz", otherQuizzes:"Other quizzes", share:"Share", correct:"Correct", wrong:"Wrong", moreResults:"Show 10 more results", expandAll:"Show all", playNow:"Play now", loadMoreQuizzes:"Show 10 more quizzes", showAll:"Show all"
};

const DETAIL_EN = {
  viewRecentResult:"View recent result",
  createMyQuiz:"Create my quiz", reportError:"Report question error", reportHelp:"Tell us what is wrong with this question. The quiz and question identifiers will be included for review.", reportReason:"Issue type", reportWrongAnswer:"Wrong answer", reportQuestionError:"Question or choices are incorrect", reportBrokenMedia:"Image or video does not work", reportOther:"Other", reportPlaceholder:"Add details to help us verify the issue (optional)", submitReport:"Submit report", reporting:"Submitting...", reportSuccess:"Your report was submitted.", reportLogin:"Please log in to report an issue.", reportFailed:"The report could not be submitted.", close:"Close",
  choice:"Choice", timeout:"Time expired", answerRequired:"Enter an answer or choose ‘I don't know’.", skipped:"I don't know · skipped", skippedPlain:"Skipped", restartConfirm:"Erase your current progress and restart?", finishConfirm:"Count the remaining questions as wrong and view the result?", noOtherQuiz:"No other quiz was found.", randomLoadFailed:"Could not load a random quiz.", copied:"Result link copied.", shareSummary:"{{correct}} correct out of {{total}} questions! ({{rate}}%)", totalQuestions:"{{count}} questions", questionCount:"Number of questions", allCount:"All {{count}}", timeLimit:"Time limit", noLimit:"None", seconds:"{{count}} sec", shuffleQuestions:"Shuffle questions", shuffleHelp:"Randomly selects the chosen number of questions from the full set.", on:"ON", off:"OFF", revealMethod:"When to reveal answers", revealImmediate:"After each question", revealFinal:"Only in results", revealBoth:"Both", startQuiz:"Start quiz", preparingTitle:"Preparing question media", preparingHelp:"The quiz will start after the media is preloaded.", restart:"Restart", finishNow:"View result now", currentAccuracy:"Current accuracy", scoreLabel:"Correct", answerInput:"Enter your answer", submitAnswer:"Submit answer", skipAnswer:"I don't know · count as wrong", submitChoice:"Confirm choice", correctBang:"Correct!", incorrect:"Wrong", answerLabel:"Answer", resultView:"View results", nextQuestion:"Next question", rankingLoading:"Calculating rank and answer distribution…", rankLine:"{{rank}} / {{count}}", participantsLine:"{{count}} participants · Top {{percent}}%", distributionLine:"{{score}} correct · {{count}} people", comparisonLine:"Compared with the first {{count}} answers of players who answered at least {{count}} questions.", noRanking:"There are no comparable attempts yet.", myAnswer:"My answer", unanswered:"Not answered", questionWord:"Questions"
};
const DETAIL_KO = {
  viewRecentResult:"최근 결과 보기",
  createMyQuiz:"나도 퀴즈 만들기", reportError:"문제 오류 신고", reportHelp:"이 문제의 잘못된 부분을 알려주세요. 확인할 수 있도록 퀴즈와 문제 정보가 함께 접수됩니다.", reportReason:"오류 유형", reportWrongAnswer:"정답이 잘못됨", reportQuestionError:"문제 또는 선택지가 잘못됨", reportBrokenMedia:"이미지·영상이 나오지 않음", reportOther:"기타", reportPlaceholder:"확인에 도움이 되는 내용을 입력해주세요 (선택)", submitReport:"신고 접수", reporting:"접수 중...", reportSuccess:"문제 오류 신고가 접수되었습니다.", reportLogin:"신고하려면 로그인해주세요.", reportFailed:"신고를 접수하지 못했습니다.", close:"닫기",
  choice:"선택지", timeout:"시간 초과", answerRequired:"정답을 입력하거나 ‘모르겠어요’를 눌러주세요.", skipped:"모르겠어요 · 건너뜀", skippedPlain:"건너뜀", restartConfirm:"현재 진행 기록을 지우고 처음부터 다시 풀까요?", finishConfirm:"남은 문제는 오답으로 처리하고 결과를 볼까요?", noOtherQuiz:"다른 퀴즈 맞히기를 찾지 못했습니다.", randomLoadFailed:"랜덤 퀴즈를 불러오지 못했습니다.", copied:"결과 링크를 복사했습니다.", shareSummary:"{{total}}문제 중 {{correct}}문제 정답! ({{rate}}%)", totalQuestions:"총 {{count}}문제", questionCount:"문제 수", allCount:"전체 {{count}}", timeLimit:"제한 시간", noLimit:"없음", seconds:"{{count}}초", shuffleQuestions:"문제 순서 섞기", shuffleHelp:"선택한 문제 수만큼 전체 문제에서 무작위로 골라 출제합니다.", on:"켜짐", off:"꺼짐", revealMethod:"정답 공개 방식", revealImmediate:"문제마다 바로", revealFinal:"결과에서만", revealBoth:"둘 다", startQuiz:"퀴즈 맞히기 시작", preparingTitle:"문제 이미지를 준비하고 있어요", preparingHelp:"이미지를 미리 불러온 뒤 바로 시작합니다.", restart:"처음부터 다시", finishNow:"바로 결과 보기", currentAccuracy:"현재 정답률", scoreLabel:"정답", answerInput:"정답 입력", submitAnswer:"정답 제출", skipAnswer:"모르겠어요 · 오답으로 넘어가기", submitChoice:"선택 완료", correctBang:"정답!", incorrect:"오답", answerLabel:"정답", resultView:"결과 보기", nextQuestion:"다음 문제", rankingLoading:"등수와 정답 분포를 계산하고 있어요…", rankLine:"{{rank}}등 / {{count}}명", participantsLine:"총 참여자 {{count}}명 · 상위 {{percent}}%", distributionLine:"{{score}}개 정답 {{count}}명", comparisonLine:"{{count}}문제 이상 푼 참여자의 앞 {{count}}문제 결과와 비교했어요.", noRanking:"아직 비교할 참여 기록이 없습니다.", myAnswer:"내 답", unanswered:"미입력", questionWord:"문제"
};

const COPY = {
  en: EN,
  ko: { title:"퀴즈 맞히기", intro:"좋아하는 주제의 퀴즈 맞히기를 풀고, 나만의 문제도 만들어보세요.", create:"퀴즈 맞히기 만들기", search:"퀴즈 맞히기 검색", popular:"인기순", latest:"최신순", empty:"조건에 맞는 퀴즈 맞히기가 없습니다.", loading:"불러오는 중...", all:"전체", game:"게임", entertainment:"연예", animation:"애니 / 만화", food:"음식", sports:"스포츠", knowledge:"상식", other:"기타", questions:"문제", plays:"플레이", featured:"추천 퀴즈 맞히기", allQuizzes:"전체 퀴즈 맞히기", quizList:"퀴즈 목록", resultTitle:"퀴즈 맞히기 결과", accuracy:"정답률", retry:"다시 풀기", retryWrong:"오답만 다시 풀기", randomQuiz:"랜덤 퀴즈 풀기", otherQuizzes:"다른 퀴즈 보기", share:"공유하기", correct:"정답", wrong:"오답", moreResults:"결과 10개 더보기", expandAll:"전체 펼치기", playNow:"지금 풀기", loadMoreQuizzes:"퀴즈 10개 더보기", showAll:"전체 펼치기" },
  ja: { title:"クイズ", intro:"好きなテーマのクイズに挑戦したり、自分で作成できます。", create:"クイズを作る", search:"クイズを検索", popular:"人気", latest:"新着", empty:"該当するクイズがありません。", loading:"読み込み中...", all:"すべて", game:"ゲーム", entertainment:"芸能", animation:"アニメ・漫画", food:"食べ物", sports:"スポーツ", knowledge:"知識", other:"その他", questions:"問", plays:"プレイ", featured:"おすすめクイズ", allQuizzes:"すべてのクイズ" },
  zh: { title:"猜谜", intro:"挑战喜爱主题的测验，或创建自己的测验。", create:"创建测验", search:"搜索测验", popular:"热门", latest:"最新", empty:"没有符合条件的测验。", loading:"加载中...", all:"全部", game:"游戏", entertainment:"娱乐", animation:"动漫", food:"美食", sports:"体育", knowledge:"知识", other:"其他", questions:"题", plays:"次游玩", featured:"推荐测验", allQuizzes:"全部测验" },
  es: { title:"Quiz", intro:"Responde quizzes de tus temas favoritos o crea el tuyo.", create:"Crear quiz", search:"Buscar quizzes", popular:"Popular", latest:"Recientes", empty:"No hay quizzes con estos filtros.", loading:"Cargando...", all:"Todo", game:"Juegos", entertainment:"Entretenimiento", animation:"Anime / Manga", food:"Comida", sports:"Deportes", knowledge:"Cultura", other:"Otros", questions:"preguntas", plays:"partidas", featured:"Quizzes recomendados", allQuizzes:"Todos los quizzes" },
  fr: { title:"Quiz", intro:"Jouez à des quiz sur vos sujets préférés ou créez le vôtre.", create:"Créer un quiz", search:"Rechercher", popular:"Populaires", latest:"Récents", empty:"Aucun quiz correspondant.", loading:"Chargement...", all:"Tout", game:"Jeux", entertainment:"Divertissement", animation:"Anime / Manga", food:"Cuisine", sports:"Sports", knowledge:"Culture", other:"Autres", questions:"questions", plays:"parties", featured:"Quiz recommandés", allQuizzes:"Tous les quiz" },
  vi: { title:"Đố vui", intro:"Chơi câu đố theo chủ đề yêu thích hoặc tự tạo câu đố.", create:"Tạo câu đố", search:"Tìm câu đố", popular:"Phổ biến", latest:"Mới nhất", empty:"Không có câu đố phù hợp.", loading:"Đang tải...", all:"Tất cả", game:"Trò chơi", entertainment:"Giải trí", animation:"Anime / Manga", food:"Ẩm thực", sports:"Thể thao", knowledge:"Kiến thức", other:"Khác", questions:"câu", plays:"lượt chơi", featured:"Đố vui đề xuất", allQuizzes:"Tất cả câu đố" },
  de: { title:"Quiz", intro:"Spiele Quizze zu deinen Lieblingsthemen oder erstelle dein eigenes.", create:"Quiz erstellen", search:"Quiz suchen", popular:"Beliebt", latest:"Neu", empty:"Keine passenden Quizze.", loading:"Wird geladen...", all:"Alle", game:"Spiele", entertainment:"Unterhaltung", animation:"Anime / Manga", food:"Essen", sports:"Sport", knowledge:"Wissen", other:"Sonstiges", questions:"Fragen", plays:"Spiele", featured:"Empfohlene Quizze", allQuizzes:"Alle Quizze" },
  ru: { title:"Викторина", intro:"Проходите викторины на любимые темы или создайте свою.", create:"Создать викторину", search:"Поиск викторин", popular:"Популярные", latest:"Новые", empty:"Подходящих викторин нет.", loading:"Загрузка...", all:"Все", game:"Игры", entertainment:"Развлечения", animation:"Аниме / Манга", food:"Еда", sports:"Спорт", knowledge:"Знания", other:"Другое", questions:"вопросов", plays:"игр", featured:"Рекомендуемые", allQuizzes:"Все викторины" },
  id: { title:"Kuis", intro:"Mainkan kuis bertema favorit atau buat kuismu sendiri.", create:"Buat kuis", search:"Cari kuis", popular:"Populer", latest:"Terbaru", empty:"Tidak ada kuis yang cocok.", loading:"Memuat...", all:"Semua", game:"Game", entertainment:"Hiburan", animation:"Anime / Manga", food:"Makanan", sports:"Olahraga", knowledge:"Pengetahuan", other:"Lainnya", questions:"soal", plays:"dimainkan", featured:"Kuis rekomendasi", allQuizzes:"Semua kuis" },
  pt: { title:"Quiz", intro:"Jogue quizzes dos seus temas favoritos ou crie o seu.", create:"Criar quiz", search:"Buscar quizzes", popular:"Popular", latest:"Recentes", empty:"Nenhum quiz encontrado.", loading:"Carregando...", all:"Todos", game:"Jogos", entertainment:"Entretenimento", animation:"Anime / Mangá", food:"Comida", sports:"Esportes", knowledge:"Conhecimento", other:"Outros", questions:"perguntas", plays:"jogadas", featured:"Quizzes recomendados", allQuizzes:"Todos os quizzes" },
  hi: { title:"क्विज़", intro:"पसंदीदा विषयों पर क्विज़ खेलें या अपना बनाएं।", create:"क्विज़ बनाएं", search:"क्विज़ खोजें", popular:"लोकप्रिय", latest:"नवीनतम", empty:"कोई क्विज़ नहीं मिला।", loading:"लोड हो रहा है...", all:"सभी", game:"गेम", entertainment:"मनोरंजन", animation:"एनीमे / मंगा", food:"खाना", sports:"खेल", knowledge:"ज्ञान", other:"अन्य", questions:"प्रश्न", plays:"प्ले", featured:"सुझाए गए क्विज़", allQuizzes:"सभी क्विज़" },
  tr: { title:"Quiz", intro:"Sevdiğin konularda quiz çöz veya kendi quizini oluştur.", create:"Quiz oluştur", search:"Quiz ara", popular:"Popüler", latest:"Yeni", empty:"Eşleşen quiz yok.", loading:"Yükleniyor...", all:"Tümü", game:"Oyun", entertainment:"Eğlence", animation:"Anime / Manga", food:"Yemek", sports:"Spor", knowledge:"Bilgi", other:"Diğer", questions:"soru", plays:"oynama", featured:"Önerilen quizler", allQuizzes:"Tüm quizler" },
  th: { title:"ควิซ", intro:"เล่นควิซหัวข้อโปรดหรือสร้างควิซของคุณเอง", create:"สร้างควิซ", search:"ค้นหาควิซ", popular:"ยอดนิยม", latest:"ล่าสุด", empty:"ไม่พบควิซที่ตรงกัน", loading:"กำลังโหลด...", all:"ทั้งหมด", game:"เกม", entertainment:"บันเทิง", animation:"อนิเมะ / มังงะ", food:"อาหาร", sports:"กีฬา", knowledge:"ความรู้", other:"อื่นๆ", questions:"ข้อ", plays:"ครั้ง", featured:"ควิซแนะนำ", allQuizzes:"ควิซทั้งหมด" },
  ar: { title:"اختبار", intro:"العب اختبارات عن مواضيعك المفضلة أو أنشئ اختبارك.", create:"إنشاء اختبار", search:"بحث عن اختبار", popular:"الأكثر شعبية", latest:"الأحدث", empty:"لا توجد اختبارات مطابقة.", loading:"جارٍ التحميل...", all:"الكل", game:"ألعاب", entertainment:"ترفيه", animation:"أنمي / مانغا", food:"طعام", sports:"رياضة", knowledge:"معرفة", other:"أخرى", questions:"أسئلة", plays:"مرات لعب", featured:"اختبارات مقترحة", allQuizzes:"كل الاختبارات" },
  bn: { title:"কুইজ", intro:"পছন্দের বিষয়ে কুইজ খেলুন বা নিজের কুইজ তৈরি করুন।", create:"কুইজ তৈরি", search:"কুইজ খুঁজুন", popular:"জনপ্রিয়", latest:"সর্বশেষ", empty:"কোনো কুইজ পাওয়া যায়নি।", loading:"লোড হচ্ছে...", all:"সব", game:"গেম", entertainment:"বিনোদন", animation:"অ্যানিমে / মাঙ্গা", food:"খাবার", sports:"খেলাধুলা", knowledge:"জ্ঞান", other:"অন্যান্য", questions:"প্রশ্ন", plays:"খেলা", featured:"প্রস্তাবিত কুইজ", allQuizzes:"সব কুইজ" }
};

export function getQuizCopy(lang) {
  const code = String(lang || "en").split("-")[0];
  return { ...EN, ...DETAIL_EN, ...(COPY[code] || {}), ...(code === "ko" ? DETAIL_KO : {}) };
}
