const EN = {
  title: "Quiz", intro: "Play quizzes about your favorite topics or create your own.", create: "Create Quiz",
  search: "Search quizzes", popular: "Popular", latest: "Latest", empty: "No quizzes match these filters.", loading: "Loading...",
  all: "All", game: "Games", entertainment: "Entertainment", animation: "Anime / Manga", food: "Food", sports: "Sports",
  knowledge: "Knowledge", other: "Other", questions: "questions", plays: "plays", featured: "Featured Quizzes", allQuizzes: "All Quizzes",
  quizList:"Quiz list", resultTitle:"Quiz Result", accuracy:"Accuracy", retry:"Retry", retryWrong:"Retry wrong answers", randomQuiz:"Random quiz", otherQuizzes:"Other quizzes", share:"Share", correct:"Correct", wrong:"Wrong", moreResults:"Show 10 more results", expandAll:"Show all", playNow:"Play now", loadMoreQuizzes:"Show 10 more quizzes", showAll:"Show all"
};

const DETAIL_EN = {
  editQuiz:"Edit quiz", deleteQuiz:"Delete quiz", deletingQuiz:"Deleting...", deleteQuizConfirm:"Delete this quiz permanently?", deleteQuizLogin:"Please log in again.", deleteQuizFailed:"Could not delete the quiz.",
  viewRecentResult:"View recent result",
  createMyQuiz:"Create my quiz", reportError:"Report question error", reportHelp:"Tell us what is wrong with this question. The quiz and question identifiers will be included for review.", reportReason:"Issue type", reportWrongAnswer:"Wrong answer", reportQuestionError:"Question or choices are incorrect", reportBrokenMedia:"Image or video does not work", reportOther:"Other", reportPlaceholder:"Add details to help us verify the issue (optional)", submitReport:"Submit report", reporting:"Submitting...", reportSuccess:"Your report was submitted.", reportLogin:"Please log in to report an issue.", reportFailed:"The report could not be submitted.", close:"Close",
  choice:"Choice", timeout:"Time expired", answerRequired:"Enter an answer or choose ‘I don't know’.", skipped:"I don't know · skipped", skippedPlain:"Skipped", restartConfirm:"Erase your current progress and restart?", finishConfirm:"Count the remaining questions as wrong and view the result?", noOtherQuiz:"No other quiz was found.", randomLoadFailed:"Could not load a random quiz.", copied:"Result link copied.", shareSummary:"{{correct}} correct out of {{total}} questions! ({{rate}}%)", totalQuestions:"{{count}} questions", questionCount:"Number of questions", allCount:"All {{count}}", timeLimit:"Time limit", noLimit:"None", seconds:"{{count}} sec", shuffleQuestions:"Shuffle questions", shuffleHelp:"Randomly selects the chosen number of questions from the full set.", on:"ON", off:"OFF", revealMethod:"When to reveal answers", revealImmediate:"After each question", revealFinal:"Only in results", revealBoth:"Both", startQuiz:"Start quiz", preparingTitle:"Preparing question media", preparingHelp:"The quiz will start after the media is preloaded.", restart:"Restart", finishNow:"View result now", currentAccuracy:"Current accuracy", scoreLabel:"Correct", answerInput:"Enter your answer", submitAnswer:"Submit answer", skipAnswer:"I don't know · count as wrong", submitChoice:"Confirm choice", correctBang:"Correct!", incorrect:"Wrong", answerLabel:"Answer", resultView:"View results", nextQuestion:"Next question", rankingLoading:"Calculating rank and answer distribution…", rankLine:"{{rank}} / {{count}}", participantsLine:"{{count}} participants · Top {{percent}}%", distributionLine:"{{score}} correct · {{count}} people", comparisonLine:"Compared with the first {{count}} answers of players who answered at least {{count}} questions.", noRanking:"There are no comparable attempts yet.", myAnswer:"My answer", unanswered:"Not answered", questionWord:"Questions"
};
const DETAIL_KO = {
  editQuiz:"퀴즈 수정", deleteQuiz:"퀴즈 삭제", deletingQuiz:"삭제 중...", deleteQuizConfirm:"이 퀴즈를 영구 삭제할까요?", deleteQuizLogin:"다시 로그인해주세요.", deleteQuizFailed:"퀴즈를 삭제하지 못했습니다.",
  viewRecentResult:"최근 결과 보기",
  createMyQuiz:"나도 퀴즈 만들기", reportError:"문제 오류 신고", reportHelp:"이 문제의 잘못된 부분을 알려주세요. 확인할 수 있도록 퀴즈와 문제 정보가 함께 접수됩니다.", reportReason:"오류 유형", reportWrongAnswer:"정답이 잘못됨", reportQuestionError:"문제 또는 선택지가 잘못됨", reportBrokenMedia:"이미지·영상이 나오지 않음", reportOther:"기타", reportPlaceholder:"확인에 도움이 되는 내용을 입력해주세요 (선택)", submitReport:"신고 접수", reporting:"접수 중...", reportSuccess:"문제 오류 신고가 접수되었습니다.", reportLogin:"신고하려면 로그인해주세요.", reportFailed:"신고를 접수하지 못했습니다.", close:"닫기",
  choice:"선택지", timeout:"시간 초과", answerRequired:"정답을 입력하거나 ‘모르겠어요’를 눌러주세요.", skipped:"모르겠어요 · 건너뜀", skippedPlain:"건너뜀", restartConfirm:"현재 진행 기록을 지우고 처음부터 다시 풀까요?", finishConfirm:"남은 문제는 오답으로 처리하고 결과를 볼까요?", noOtherQuiz:"다른 퀴즈 맞히기를 찾지 못했습니다.", randomLoadFailed:"랜덤 퀴즈를 불러오지 못했습니다.", copied:"결과 링크를 복사했습니다.", shareSummary:"{{total}}문제 중 {{correct}}문제 정답! ({{rate}}%)", totalQuestions:"총 {{count}}문제", questionCount:"문제 수", allCount:"전체 {{count}}", timeLimit:"제한 시간", noLimit:"없음", seconds:"{{count}}초", shuffleQuestions:"문제 순서 섞기", shuffleHelp:"선택한 문제 수만큼 전체 문제에서 무작위로 골라 출제합니다.", on:"켜짐", off:"꺼짐", revealMethod:"정답 공개 방식", revealImmediate:"문제마다 바로", revealFinal:"결과에서만", revealBoth:"둘 다", startQuiz:"퀴즈 맞히기 시작", preparingTitle:"문제 이미지를 준비하고 있어요", preparingHelp:"이미지를 미리 불러온 뒤 바로 시작합니다.", restart:"처음부터 다시", finishNow:"바로 결과 보기", currentAccuracy:"현재 정답률", scoreLabel:"정답", answerInput:"정답 입력", submitAnswer:"정답 제출", skipAnswer:"모르겠어요 · 오답으로 넘어가기", submitChoice:"선택 완료", correctBang:"정답!", incorrect:"오답", answerLabel:"정답", resultView:"결과 보기", nextQuestion:"다음 문제", rankingLoading:"등수와 정답 분포를 계산하고 있어요…", rankLine:"{{rank}}등 / {{count}}명", participantsLine:"총 참여자 {{count}}명 · 상위 {{percent}}%", distributionLine:"{{score}}개 정답 {{count}}명", comparisonLine:"{{count}}문제 이상 푼 참여자의 앞 {{count}}문제 결과와 비교했어요.", noRanking:"아직 비교할 참여 기록이 없습니다.", myAnswer:"내 답", unanswered:"미입력", questionWord:"문제"
};

const DETAIL_JA = {
  editQuiz:"クイズを編集", deleteQuiz:"クイズを削除", deletingQuiz:"削除中…", deleteQuizConfirm:"このクイズを完全に削除しますか？", deleteQuizLogin:"もう一度ログインしてください。", deleteQuizFailed:"クイズを削除できませんでした。",
  quizList:"クイズ一覧", resultTitle:"クイズ結果", accuracy:"正答率", retry:"もう一度挑戦", retryWrong:"間違えた問題だけ再挑戦", randomQuiz:"ランダムクイズ", otherQuizzes:"他のクイズ", share:"共有", correct:"正解", wrong:"不正解", moreResults:"結果を10件追加表示", expandAll:"すべて表示", playNow:"今すぐ挑戦", loadMoreQuizzes:"クイズを10件追加表示", showAll:"すべて表示",
  viewRecentResult:"最近の結果を見る", createMyQuiz:"自分もクイズを作る", reportError:"問題の誤りを報告", reportHelp:"この問題の誤っている箇所をお知らせください。確認用にクイズと問題の情報も送信されます。", reportReason:"問題の種類", reportWrongAnswer:"正解が間違っている", reportQuestionError:"問題文または選択肢が間違っている", reportBrokenMedia:"画像・動画が表示されない", reportOther:"その他", reportPlaceholder:"確認に役立つ詳細を入力してください（任意）", submitReport:"報告する", reporting:"送信中…", reportSuccess:"問題の報告を送信しました。", reportLogin:"報告するにはログインしてください。", reportFailed:"報告を送信できませんでした。", close:"閉じる",
  choice:"選択肢", timeout:"時間切れ", answerRequired:"答えを入力するか「わからない」を選んでください。", skipped:"わからない・スキップ", skippedPlain:"スキップ", restartConfirm:"現在の進行状況を消して最初からやり直しますか？", finishConfirm:"残りの問題を不正解として結果を表示しますか？", noOtherQuiz:"他のクイズが見つかりませんでした。", randomLoadFailed:"ランダムクイズを読み込めませんでした。", copied:"結果のリンクをコピーしました。", shareSummary:"{{total}}問中{{correct}}問正解！（{{rate}}%）", totalQuestions:"全{{count}}問", questionCount:"問題数", allCount:"全{{count}}問", timeLimit:"制限時間", noLimit:"なし", seconds:"{{count}}秒", shuffleQuestions:"問題をシャッフル", shuffleHelp:"全問題から選択した問題数をランダムに出題します。", on:"オン", off:"オフ", revealMethod:"正解を表示するタイミング", revealImmediate:"各問題の直後", revealFinal:"結果画面のみ", revealBoth:"両方", startQuiz:"クイズを開始", preparingTitle:"問題のメディアを準備中", preparingHelp:"画像の読み込みが完了すると開始します。", restart:"最初からやり直す", finishNow:"今すぐ結果を見る", currentAccuracy:"現在の正答率", scoreLabel:"正解", answerInput:"答えを入力", submitAnswer:"回答を送信", skipAnswer:"わからない・不正解として次へ", submitChoice:"選択を確定", correctBang:"正解！", incorrect:"不正解", answerLabel:"正解", resultView:"結果を見る", nextQuestion:"次の問題", rankingLoading:"順位と正解分布を計算中…", rankLine:"{{rank}}位 / {{count}}人", participantsLine:"参加者{{count}}人・上位{{percent}}%", distributionLine:"{{score}}問正解・{{count}}人", comparisonLine:"{{count}}問以上回答した参加者の最初の{{count}}問と比較しています。", noRanking:"比較できる回答記録がまだありません。", myAnswer:"自分の回答", unanswered:"未回答", questionWord:"問題"
};

// Core setup/play/result labels for every supported locale. Longer help and
// report copy still falls back safely, while all primary quiz controls remain
// in the language selected in the header.
const DETAIL_ALL = {
  zh:{quizList:"测验列表",resultTitle:"测验结果",accuracy:"正确率",retry:"重新挑战",retryWrong:"只重做错题",randomQuiz:"随机测验",otherQuizzes:"其他测验",share:"分享",correct:"正确",wrong:"错误",viewRecentResult:"查看最近结果",createMyQuiz:"我也要创建测验",questionCount:"题目数量",allCount:"全部 {{count}} 题",timeLimit:"时间限制",noLimit:"无限制",seconds:"{{count}} 秒",shuffleQuestions:"随机打乱题目",shuffleHelp:"从全部题目中随机抽取所选数量。",on:"开启",off:"关闭",revealMethod:"答案公布方式",revealImmediate:"每题结束后",revealFinal:"仅在结果中",revealBoth:"两者都显示",startQuiz:"开始测验",restart:"重新开始",finishNow:"立即查看结果",currentAccuracy:"当前正确率",scoreLabel:"正确",answerInput:"输入答案",submitAnswer:"提交答案",skipAnswer:"不知道・按错误处理",submitChoice:"确认选择",correctBang:"回答正确！",incorrect:"回答错误",answerLabel:"答案",resultView:"查看结果",nextQuestion:"下一题",myAnswer:"我的答案",unanswered:"未回答",questionWord:"题目"},
  es:{quizList:"Lista de quizzes",resultTitle:"Resultado del quiz",accuracy:"Aciertos",retry:"Reintentar",retryWrong:"Repetir incorrectas",randomQuiz:"Quiz aleatorio",otherQuizzes:"Otros quizzes",share:"Compartir",correct:"Correctas",wrong:"Incorrectas",viewRecentResult:"Ver resultado reciente",createMyQuiz:"Crear mi quiz",questionCount:"Número de preguntas",allCount:"Todas ({{count}})",timeLimit:"Límite de tiempo",noLimit:"Sin límite",seconds:"{{count}} s",shuffleQuestions:"Mezclar preguntas",shuffleHelp:"Selecciona al azar el número elegido de preguntas del conjunto completo.",on:"Sí",off:"No",revealMethod:"Cuándo mostrar respuestas",revealImmediate:"Después de cada pregunta",revealFinal:"Solo en resultados",revealBoth:"Ambos",startQuiz:"Empezar quiz",restart:"Reiniciar",finishNow:"Ver resultado ahora",currentAccuracy:"Aciertos actuales",scoreLabel:"Correctas",answerInput:"Escribe tu respuesta",submitAnswer:"Enviar respuesta",skipAnswer:"No lo sé · contar como error",submitChoice:"Confirmar selección",correctBang:"¡Correcto!",incorrect:"Incorrecto",answerLabel:"Respuesta",resultView:"Ver resultados",nextQuestion:"Siguiente pregunta",myAnswer:"Mi respuesta",unanswered:"Sin responder",questionWord:"Preguntas"},
  fr:{quizList:"Liste des quiz",resultTitle:"Résultat du quiz",accuracy:"Précision",retry:"Réessayer",retryWrong:"Rejouer les erreurs",randomQuiz:"Quiz aléatoire",otherQuizzes:"Autres quiz",share:"Partager",correct:"Correct",wrong:"Incorrect",viewRecentResult:"Voir le résultat récent",createMyQuiz:"Créer mon quiz",questionCount:"Nombre de questions",allCount:"Toutes ({{count}})",timeLimit:"Temps limite",noLimit:"Aucun",seconds:"{{count}} s",shuffleQuestions:"Mélanger les questions",shuffleHelp:"Sélectionne aléatoirement le nombre choisi de questions.",on:"Oui",off:"Non",revealMethod:"Afficher les réponses",revealImmediate:"Après chaque question",revealFinal:"Seulement dans les résultats",revealBoth:"Les deux",startQuiz:"Commencer le quiz",restart:"Recommencer",finishNow:"Voir le résultat",currentAccuracy:"Précision actuelle",scoreLabel:"Bonnes réponses",answerInput:"Saisissez votre réponse",submitAnswer:"Valider",skipAnswer:"Je ne sais pas · compter faux",submitChoice:"Confirmer",correctBang:"Bonne réponse !",incorrect:"Incorrect",answerLabel:"Réponse",resultView:"Voir les résultats",nextQuestion:"Question suivante",myAnswer:"Ma réponse",unanswered:"Sans réponse",questionWord:"Questions"},
  vi:{quizList:"Danh sách câu đố",resultTitle:"Kết quả",accuracy:"Độ chính xác",retry:"Chơi lại",retryWrong:"Làm lại câu sai",randomQuiz:"Câu đố ngẫu nhiên",otherQuizzes:"Câu đố khác",share:"Chia sẻ",correct:"Đúng",wrong:"Sai",viewRecentResult:"Xem kết quả gần đây",createMyQuiz:"Tạo câu đố của tôi",questionCount:"Số câu hỏi",allCount:"Tất cả {{count}}",timeLimit:"Giới hạn thời gian",noLimit:"Không",seconds:"{{count}} giây",shuffleQuestions:"Trộn câu hỏi",shuffleHelp:"Chọn ngẫu nhiên số câu hỏi đã chọn từ toàn bộ bộ đề.",on:"Bật",off:"Tắt",revealMethod:"Thời điểm hiện đáp án",revealImmediate:"Sau mỗi câu",revealFinal:"Chỉ ở kết quả",revealBoth:"Cả hai",startQuiz:"Bắt đầu",restart:"Làm lại",finishNow:"Xem kết quả ngay",currentAccuracy:"Tỷ lệ đúng hiện tại",scoreLabel:"Đúng",answerInput:"Nhập câu trả lời",submitAnswer:"Gửi đáp án",skipAnswer:"Không biết · tính là sai",submitChoice:"Xác nhận lựa chọn",correctBang:"Chính xác!",incorrect:"Sai",answerLabel:"Đáp án",resultView:"Xem kết quả",nextQuestion:"Câu tiếp theo",myAnswer:"Câu trả lời của tôi",unanswered:"Chưa trả lời",questionWord:"Câu hỏi"},
  de:{quizList:"Quizliste",resultTitle:"Quiz-Ergebnis",accuracy:"Genauigkeit",retry:"Erneut versuchen",retryWrong:"Falsche wiederholen",randomQuiz:"Zufälliges Quiz",otherQuizzes:"Andere Quizze",share:"Teilen",correct:"Richtig",wrong:"Falsch",viewRecentResult:"Letztes Ergebnis ansehen",createMyQuiz:"Eigenes Quiz erstellen",questionCount:"Anzahl der Fragen",allCount:"Alle {{count}}",timeLimit:"Zeitlimit",noLimit:"Keins",seconds:"{{count}} Sek.",shuffleQuestions:"Fragen mischen",shuffleHelp:"Wählt die gewünschte Anzahl zufällig aus allen Fragen aus.",on:"Ein",off:"Aus",revealMethod:"Antworten anzeigen",revealImmediate:"Nach jeder Frage",revealFinal:"Nur im Ergebnis",revealBoth:"Beides",startQuiz:"Quiz starten",restart:"Neu starten",finishNow:"Ergebnis ansehen",currentAccuracy:"Aktuelle Genauigkeit",scoreLabel:"Richtig",answerInput:"Antwort eingeben",submitAnswer:"Antwort senden",skipAnswer:"Weiß nicht · als falsch zählen",submitChoice:"Auswahl bestätigen",correctBang:"Richtig!",incorrect:"Falsch",answerLabel:"Antwort",resultView:"Ergebnisse ansehen",nextQuestion:"Nächste Frage",myAnswer:"Meine Antwort",unanswered:"Nicht beantwortet",questionWord:"Fragen"},
  ru:{quizList:"Список викторин",resultTitle:"Результат викторины",accuracy:"Точность",retry:"Пройти снова",retryWrong:"Повторить ошибки",randomQuiz:"Случайная викторина",otherQuizzes:"Другие викторины",share:"Поделиться",correct:"Верно",wrong:"Неверно",viewRecentResult:"Последний результат",createMyQuiz:"Создать викторину",questionCount:"Количество вопросов",allCount:"Все {{count}}",timeLimit:"Ограничение времени",noLimit:"Нет",seconds:"{{count}} сек.",shuffleQuestions:"Перемешать вопросы",shuffleHelp:"Случайно выбирает указанное количество вопросов из полного набора.",on:"Вкл.",off:"Выкл.",revealMethod:"Когда показывать ответы",revealImmediate:"После каждого вопроса",revealFinal:"Только в результатах",revealBoth:"Оба варианта",startQuiz:"Начать викторину",restart:"Начать заново",finishNow:"Показать результат",currentAccuracy:"Текущая точность",scoreLabel:"Верно",answerInput:"Введите ответ",submitAnswer:"Отправить ответ",skipAnswer:"Не знаю · засчитать ошибкой",submitChoice:"Подтвердить выбор",correctBang:"Верно!",incorrect:"Неверно",answerLabel:"Ответ",resultView:"Результаты",nextQuestion:"Следующий вопрос",myAnswer:"Мой ответ",unanswered:"Без ответа",questionWord:"Вопросы"},
  id:{quizList:"Daftar kuis",resultTitle:"Hasil kuis",accuracy:"Akurasi",retry:"Coba lagi",retryWrong:"Ulangi jawaban salah",randomQuiz:"Kuis acak",otherQuizzes:"Kuis lainnya",share:"Bagikan",correct:"Benar",wrong:"Salah",viewRecentResult:"Lihat hasil terakhir",createMyQuiz:"Buat kuis saya",questionCount:"Jumlah soal",allCount:"Semua {{count}}",timeLimit:"Batas waktu",noLimit:"Tidak ada",seconds:"{{count}} detik",shuffleQuestions:"Acak soal",shuffleHelp:"Memilih jumlah soal yang dipilih secara acak dari seluruh set.",on:"Aktif",off:"Nonaktif",revealMethod:"Kapan jawaban ditampilkan",revealImmediate:"Setelah setiap soal",revealFinal:"Hanya di hasil",revealBoth:"Keduanya",startQuiz:"Mulai kuis",restart:"Mulai ulang",finishNow:"Lihat hasil sekarang",currentAccuracy:"Akurasi saat ini",scoreLabel:"Benar",answerInput:"Masukkan jawaban",submitAnswer:"Kirim jawaban",skipAnswer:"Tidak tahu · hitung salah",submitChoice:"Konfirmasi pilihan",correctBang:"Benar!",incorrect:"Salah",answerLabel:"Jawaban",resultView:"Lihat hasil",nextQuestion:"Soal berikutnya",myAnswer:"Jawaban saya",unanswered:"Belum dijawab",questionWord:"Soal"},
  pt:{quizList:"Lista de quizzes",resultTitle:"Resultado do quiz",accuracy:"Precisão",retry:"Tentar novamente",retryWrong:"Refazer erradas",randomQuiz:"Quiz aleatório",otherQuizzes:"Outros quizzes",share:"Compartilhar",correct:"Corretas",wrong:"Erradas",viewRecentResult:"Ver resultado recente",createMyQuiz:"Criar meu quiz",questionCount:"Número de perguntas",allCount:"Todas {{count}}",timeLimit:"Limite de tempo",noLimit:"Nenhum",seconds:"{{count}} s",shuffleQuestions:"Embaralhar perguntas",shuffleHelp:"Seleciona aleatoriamente a quantidade escolhida do conjunto completo.",on:"Ligado",off:"Desligado",revealMethod:"Quando mostrar respostas",revealImmediate:"Após cada pergunta",revealFinal:"Somente nos resultados",revealBoth:"Ambos",startQuiz:"Começar quiz",restart:"Reiniciar",finishNow:"Ver resultado agora",currentAccuracy:"Precisão atual",scoreLabel:"Corretas",answerInput:"Digite sua resposta",submitAnswer:"Enviar resposta",skipAnswer:"Não sei · contar como errada",submitChoice:"Confirmar escolha",correctBang:"Correto!",incorrect:"Incorreto",answerLabel:"Resposta",resultView:"Ver resultados",nextQuestion:"Próxima pergunta",myAnswer:"Minha resposta",unanswered:"Sem resposta",questionWord:"Perguntas"},
  hi:{quizList:"क्विज़ सूची",resultTitle:"क्विज़ परिणाम",accuracy:"सटीकता",retry:"फिर प्रयास करें",retryWrong:"गलत उत्तर दोबारा",randomQuiz:"रैंडम क्विज़",otherQuizzes:"अन्य क्विज़",share:"साझा करें",correct:"सही",wrong:"गलत",viewRecentResult:"हाल का परिणाम देखें",createMyQuiz:"अपना क्विज़ बनाएं",questionCount:"प्रश्नों की संख्या",allCount:"सभी {{count}}",timeLimit:"समय सीमा",noLimit:"कोई नहीं",seconds:"{{count}} सेकंड",shuffleQuestions:"प्रश्न मिलाएं",shuffleHelp:"पूरे सेट से चुनी गई संख्या में प्रश्न यादृच्छिक रूप से चुनता है।",on:"चालू",off:"बंद",revealMethod:"उत्तर कब दिखाएं",revealImmediate:"हर प्रश्न के बाद",revealFinal:"केवल परिणाम में",revealBoth:"दोनों",startQuiz:"क्विज़ शुरू करें",restart:"फिर शुरू करें",finishNow:"परिणाम देखें",currentAccuracy:"वर्तमान सटीकता",scoreLabel:"सही",answerInput:"उत्तर लिखें",submitAnswer:"उत्तर जमा करें",skipAnswer:"पता नहीं · गलत मानें",submitChoice:"चयन पक्का करें",correctBang:"सही!",incorrect:"गलत",answerLabel:"उत्तर",resultView:"परिणाम देखें",nextQuestion:"अगला प्रश्न",myAnswer:"मेरा उत्तर",unanswered:"उत्तर नहीं दिया",questionWord:"प्रश्न"},
  tr:{quizList:"Quiz listesi",resultTitle:"Quiz sonucu",accuracy:"Doğruluk",retry:"Tekrar dene",retryWrong:"Yanlışları tekrar çöz",randomQuiz:"Rastgele quiz",otherQuizzes:"Diğer quizler",share:"Paylaş",correct:"Doğru",wrong:"Yanlış",viewRecentResult:"Son sonucu gör",createMyQuiz:"Quizimi oluştur",questionCount:"Soru sayısı",allCount:"Tümü {{count}}",timeLimit:"Süre sınırı",noLimit:"Yok",seconds:"{{count}} sn",shuffleQuestions:"Soruları karıştır",shuffleHelp:"Tüm setten seçilen sayıda soruyu rastgele seçer.",on:"Açık",off:"Kapalı",revealMethod:"Cevapları gösterme zamanı",revealImmediate:"Her sorudan sonra",revealFinal:"Yalnız sonuçlarda",revealBoth:"İkisi de",startQuiz:"Quizi başlat",restart:"Yeniden başlat",finishNow:"Sonucu şimdi gör",currentAccuracy:"Güncel doğruluk",scoreLabel:"Doğru",answerInput:"Cevabını gir",submitAnswer:"Cevabı gönder",skipAnswer:"Bilmiyorum · yanlış say",submitChoice:"Seçimi onayla",correctBang:"Doğru!",incorrect:"Yanlış",answerLabel:"Cevap",resultView:"Sonuçları gör",nextQuestion:"Sonraki soru",myAnswer:"Cevabım",unanswered:"Cevapsız",questionWord:"Sorular"},
  th:{quizList:"รายการควิซ",resultTitle:"ผลควิซ",accuracy:"ความแม่นยำ",retry:"ลองอีกครั้ง",retryWrong:"ทำข้อที่ผิดใหม่",randomQuiz:"ควิซสุ่ม",otherQuizzes:"ควิซอื่น",share:"แชร์",correct:"ถูก",wrong:"ผิด",viewRecentResult:"ดูผลล่าสุด",createMyQuiz:"สร้างควิซของฉัน",questionCount:"จำนวนคำถาม",allCount:"ทั้งหมด {{count}}",timeLimit:"จำกัดเวลา",noLimit:"ไม่มี",seconds:"{{count}} วินาที",shuffleQuestions:"สุ่มคำถาม",shuffleHelp:"สุ่มเลือกคำถามตามจำนวนที่เลือกจากชุดทั้งหมด",on:"เปิด",off:"ปิด",revealMethod:"เวลาที่แสดงคำตอบ",revealImmediate:"หลังแต่ละข้อ",revealFinal:"เฉพาะหน้าผลลัพธ์",revealBoth:"ทั้งสอง",startQuiz:"เริ่มควิซ",restart:"เริ่มใหม่",finishNow:"ดูผลทันที",currentAccuracy:"ความแม่นยำปัจจุบัน",scoreLabel:"ถูก",answerInput:"กรอกคำตอบ",submitAnswer:"ส่งคำตอบ",skipAnswer:"ไม่ทราบ · นับว่าผิด",submitChoice:"ยืนยันตัวเลือก",correctBang:"ถูกต้อง!",incorrect:"ผิด",answerLabel:"คำตอบ",resultView:"ดูผลลัพธ์",nextQuestion:"ข้อต่อไป",myAnswer:"คำตอบของฉัน",unanswered:"ยังไม่ตอบ",questionWord:"คำถาม"},
  ar:{quizList:"قائمة الاختبارات",resultTitle:"نتيجة الاختبار",accuracy:"الدقة",retry:"إعادة المحاولة",retryWrong:"إعادة الإجابات الخاطئة",randomQuiz:"اختبار عشوائي",otherQuizzes:"اختبارات أخرى",share:"مشاركة",correct:"صحيح",wrong:"خطأ",viewRecentResult:"عرض النتيجة الأخيرة",createMyQuiz:"إنشاء اختباري",questionCount:"عدد الأسئلة",allCount:"الكل {{count}}",timeLimit:"الحد الزمني",noLimit:"بدون",seconds:"{{count}} ثانية",shuffleQuestions:"خلط الأسئلة",shuffleHelp:"يختار عشوائياً العدد المحدد من مجموعة الأسئلة كاملة.",on:"تشغيل",off:"إيقاف",revealMethod:"وقت إظهار الإجابات",revealImmediate:"بعد كل سؤال",revealFinal:"في النتائج فقط",revealBoth:"كلاهما",startQuiz:"بدء الاختبار",restart:"إعادة البدء",finishNow:"عرض النتيجة الآن",currentAccuracy:"الدقة الحالية",scoreLabel:"صحيح",answerInput:"أدخل إجابتك",submitAnswer:"إرسال الإجابة",skipAnswer:"لا أعرف · احتسابها خطأ",submitChoice:"تأكيد الاختيار",correctBang:"صحيح!",incorrect:"خطأ",answerLabel:"الإجابة",resultView:"عرض النتائج",nextQuestion:"السؤال التالي",myAnswer:"إجابتي",unanswered:"بدون إجابة",questionWord:"الأسئلة"},
  bn:{quizList:"কুইজ তালিকা",resultTitle:"কুইজের ফলাফল",accuracy:"সঠিকতার হার",retry:"আবার চেষ্টা",retryWrong:"ভুলগুলো আবার দিন",randomQuiz:"এলোমেলো কুইজ",otherQuizzes:"অন্যান্য কুইজ",share:"শেয়ার",correct:"সঠিক",wrong:"ভুল",viewRecentResult:"সাম্প্রতিক ফল দেখুন",createMyQuiz:"আমার কুইজ তৈরি",questionCount:"প্রশ্নের সংখ্যা",allCount:"সব {{count}}",timeLimit:"সময়সীমা",noLimit:"নেই",seconds:"{{count}} সেকেন্ড",shuffleQuestions:"প্রশ্ন এলোমেলো করুন",shuffleHelp:"সম্পূর্ণ সেট থেকে নির্বাচিত সংখ্যক প্রশ্ন এলোমেলোভাবে বেছে নেয়।",on:"চালু",off:"বন্ধ",revealMethod:"উত্তর দেখানোর সময়",revealImmediate:"প্রতিটি প্রশ্নের পরে",revealFinal:"শুধু ফলাফলে",revealBoth:"দুটিই",startQuiz:"কুইজ শুরু",restart:"আবার শুরু",finishNow:"এখন ফল দেখুন",currentAccuracy:"বর্তমান সঠিকতা",scoreLabel:"সঠিক",answerInput:"উত্তর লিখুন",submitAnswer:"উত্তর জমা দিন",skipAnswer:"জানি না · ভুল হিসেবে গণনা",submitChoice:"পছন্দ নিশ্চিত করুন",correctBang:"সঠিক!",incorrect:"ভুল",answerLabel:"উত্তর",resultView:"ফলাফল দেখুন",nextQuestion:"পরের প্রশ্ন",myAnswer:"আমার উত্তর",unanswered:"উত্তর দেওয়া হয়নি",questionWord:"প্রশ্ন"}
};

const PLAY_NOW = {
  ko:"지금 풀기", ja:"今すぐ挑戦", zh:"立即挑战", es:"Jugar ahora",
  fr:"Jouer", vi:"Chơi ngay", de:"Jetzt spielen", ru:"Начать",
  id:"Main sekarang", pt:"Jogar agora", hi:"अभी खेलें", tr:"Şimdi oyna",
  th:"เล่นเลย", ar:"ابدأ الآن", bn:"এখন খেলুন"
};

const COPY = {
  en: EN,
  ko: { title:"퀴즈 맞히기", intro:"좋아하는 주제의 퀴즈 맞히기를 풀고, 나만의 문제도 만들어보세요.", create:"퀴즈 맞히기 만들기", search:"퀴즈 맞히기 검색", popular:"인기순", latest:"최신순", empty:"조건에 맞는 퀴즈 맞히기가 없습니다.", loading:"불러오는 중...", all:"전체", game:"게임", entertainment:"연예", animation:"애니 / 만화", food:"음식", sports:"스포츠", knowledge:"상식", other:"기타", questions:"문제", plays:"플레이", featured:"추천 퀴즈 맞히기", allQuizzes:"전체 퀴즈 맞히기", quizList:"퀴즈 목록", resultTitle:"퀴즈 맞히기 결과", accuracy:"정답률", retry:"다시 풀기", retryWrong:"오답만 다시 풀기", randomQuiz:"랜덤 퀴즈 풀기", otherQuizzes:"다른 퀴즈 보기", share:"공유하기", correct:"정답", wrong:"오답", moreResults:"결과 10개 더보기", expandAll:"전체 펼치기", playNow:"지금 풀기", loadMoreQuizzes:"퀴즈 10개 더보기", showAll:"전체 펼치기" },
  ja: { title:"クイズ", intro:"好きなテーマのクイズに挑戦したり、自分で作成できます。", create:"クイズを作る", search:"クイズを検索", popular:"人気", latest:"新着", empty:"該当するクイズがありません。", loading:"読み込み中...", all:"すべて", game:"ゲーム", entertainment:"芸能", animation:"アニメ・漫画", food:"食べ物", sports:"スポーツ", knowledge:"知識", other:"その他", questions:"問", plays:"プレイ", featured:"おすすめクイズ", allQuizzes:"すべてのクイズ" },
  zh: { title:"猜谜", intro:"挑战喜爱主题的测验，或创建自己的测验。", create:"创建测验", search:"搜索测验", popular:"热门", latest:"最新", empty:"没有符合条件的测验。", loading:"加载中...", all:"全部", game:"游戏", entertainment:"娱乐", animation:"动漫", food:"美食", sports:"体育", knowledge:"知识", other:"其他", questions:"题", plays:"次游玩", featured:"推荐测验", allQuizzes:"全部测验" },
  es: { title:"Quiz", intro:"Responde quizzes de tus temas favoritos o crea el tuyo.", create:"Crear quiz", search:"Buscar quizzes", popular:"Popular", latest:"Recientes", empty:"No hay quizzes con estos filtros.", loading:"Cargando...", all:"Todo", game:"Juegos", entertainment:"Entretenimiento", animation:"Anime / Manga", food:"Comida", sports:"Deportes", knowledge:"Cultura", other:"Otros", questions:"preguntas", plays:"partidas", featured:"Quizzes recomendados", allQuizzes:"Todos los quizzes" },
  fr: { title:"Quiz", intro:"Jouez à des quiz sur vos sujets préférés ou créez le vôtre.", create:"Créer un quiz", search:"Rechercher", popular:"Populaires", latest:"Récents", empty:"Aucun quiz correspondant.", loading:"Chargement...", all:"Tout", game:"Jeux", entertainment:"Divertissement", animation:"Anime / Manga", food:"Cuisine", sports:"Sports", knowledge:"Culture", other:"Autres", questions:"questions", plays:"parties", featured:"Quiz recommandés", allQuizzes:"Tous les quiz" },
  vi: { title:"Đố vui", intro:"Chơi câu đố theo chủ đề yêu thích hoặc tự tạo câu đố.", create:"Tạo câu đố", search:"Tìm câu đố", popular:"Phổ biến", latest:"Mới nhất", empty:"Không có câu đố phù hợp.", loading:"Đang tải...", all:"Tất cả", game:"Trò chơi", entertainment:"Giải trí", animation:"Anime / Manga", food:"Ẩm thực", sports:"Thể thao", knowledge:"Kiến thức", other:"Khác", questions:"câu", plays:"lượt chơi", featured:"Đố vui đề xuất", allQuizzes:"Tất cả câu đố" },
  de: { title:"Quiz", intro:"Spiele Quizze zu deinen Lieblingsthemen oder erstelle dein eigenes.", create:"Quiz erstellen", search:"Quiz suchen", popular:"Beliebt", latest:"Neu", empty:"Keine passenden Quizze.", loading:"Wird geladen...", all:"Alle", game:"Spiele", entertainment:"Unterhaltung", animation:"Anime / Manga", food:"Essen", sports:"Sport", knowledge:"Wissen", other:"Sonstiges", questions:"Fragen", plays:"Spiele", featured:"Empfohlene Quizze", allQuizzes:"Alle Quizze" },
  ru: { title:"Викторина", intro:"Проходите викторины на любимые темы или создайте свою.", create:"Создать викторину", search:"Поиск викторин", popular:"Популярные", latest:"Новые", empty:"Подходящих викторин нет.", loading:"Загрузка...", all:"Все", game:"Игры", entertainment:"Развлечения", animation:"Аниме / Манга", food:"Еда", sports:"Спорт", knowledge:"Знания", other:"Другое", questions:"вопросов", plays:"игр", featured:"Рекомендуемые", allQuizzes:"Все викторины" },
  id: { title:"Kuis", intro:"Mainkan kuis bertema favorit atau buat kuismu sendiri.", create:"Buat kuis", search:"Cari kuis", popular:"Populer", latest:"Terbaru", empty:"Tidak ada kuis yang cocok.", loading:"Memuat...", all:"Semua", game:"Game", entertainment:"Hiburan", animation:"Anime / Manga", food:"Makanan", sports:"Olahraga", knowledge:"Pengetahuan", other:"Lainnya", questions:"soal", plays:"dimainkan", featured:"Kuis rekomendasi", allQuizzes:"Semua kuis" },
  pt: { title:"Quiz", intro:"Jogue quizzes dos seus temas favoritos ou crie o seu.", create:"Criar quiz", search:"Buscar quizzes", popular:"Popular", latest:"Recentes", empty:"Nenhum quiz encontrado.", loading:"Carregando...", all:"Todos", game:"Jogos", entertainment:"Entretenimento", animation:"Anime / Mangá", food:"Comida", sports:"Esportes", knowledge:"Conhecimento", other:"Outros", questions:"perguntas", plays:"jogadas", featured:"Quizzes recomendados", allQuizzes:"Todos os quizzes" },
  hi: { title:"क्विज़", intro:"पसंदीदा विषयों पर क्विज़ खेलें या अपना बनाएं।", create:"क्विज़ बनाएं", search:"क्विज़ खोजें", popular:"लोकप्रिय", latest:"नवीनतम", empty:"कोई क्विज़ नहीं मिला।", loading:"लोड हो रहा है...", all:"सभी", game:"गेम", entertainment:"मनोरंजन", animation:"एनीमे / मंगा", food:"खाना", sports:"खेल", knowledge:"ज्ञान", other:"अन्य", questions:"प्रश्न", plays:"प्ले", featured:"सुझाए गए क्विज़", allQuizzes:"सभी क्विज़" },
  tr: { title:"Quiz", intro:"Sevdiğin konularda quiz çöz veya kendi quizini oluştur.", create:"Quiz oluştur", search:"Quiz ara", popular:"Popüler", latest:"Yeni", empty:"Eşleşen quiz yok.", loading:"Yükleniyor...", all:"Tümü", game:"Oyun", entertainment:"Eğlence", animation:"Anime / Manga", food:"Yemek", sports:"Spor", knowledge:"Bilgi", other:"Diğer", questions:"soru", plays:"oynama", featured:"Önerilen quizler", allQuizzes:"Tüm quizler" },
  th: { title:"ควิซ", intro:"เล่นควิซหัวข้อโปรดหรือสร้างควิซของคุณเอง", create:"สร้างควิซ", search:"ค้นหาควิซ", popular:"ยอดนิยม", latest:"ล่าสุด", empty:"ไม่พบควิซที่ตรงกัน", loading:"กำลังโหลด...", all:"ทั้งหมด", game:"เกม", entertainment:"บันเทิง", animation:"อนิเมะ / มังงะ", food:"อาหาร", sports:"กีฬา", knowledge:"ความรู้", other:"อื่นๆ", questions:"ข้อ", plays:"ครั้ง", featured:"ควิซแนะนำ", allQuizzes:"ควิซทั้งหมด" },
  ar: { title:"اختبار", intro:"العب اختبارات عن مواضيعك المفضلة أو أنشئ اختبارك.", create:"إنشاء اختبار", search:"بحث عن اختبار", popular:"الأكثر شعبية", latest:"الأحدث", empty:"لا توجد اختبارات مطابقة.", loading:"جارٍ التحميل...", all:"الكل", game:"ألعاب", entertainment:"ترفيه", animation:"أنمي / مانغا", food:"طعام", sports:"رياضة", knowledge:"معرفة", other:"أخرى", questions:"أسئلة", plays:"مرات لعب", featured:"اختبارات مقترحة", allQuizzes:"كل الاختبارات" },
  bn: { title:"কুইজ", intro:"পছন্দের বিষয়ে কুইজ খেলুন বা নিজের কুইজ তৈরি করুন।", create:"কুইজ তৈরি", search:"কুইজ খুঁজুন", popular:"জনপ্রিয়", latest:"সর্বশেষ", empty:"কোনো কুইজ পাওয়া যায়নি।", loading:"লোড হচ্ছে...", all:"সব", game:"গেম", entertainment:"বিনোদন", animation:"অ্যানিমে / মাঙ্গা", food:"খাবার", sports:"খেলাধুলা", knowledge:"জ্ঞান", other:"অন্যান্য", questions:"প্রশ্ন", plays:"খেলা", featured:"প্রস্তাবিত কুইজ", allQuizzes:"সব কুইজ" }
};

export function getQuizCopy(lang) {
  const code = String(lang || "en").split("-")[0];
  const result = {
    ...EN,
    ...DETAIL_EN,
    ...(COPY[code] || {}),
    ...(code === "ko" ? DETAIL_KO : {}),
    ...(code === "ja" ? DETAIL_JA : {}),
    ...(DETAIL_ALL[code] || {}),
  };
  if (code === "ko") result.create = "퀴즈 만들기";
  if (PLAY_NOW[code]) result.playNow = PLAY_NOW[code];
  return result;
}
